---
version: 2
models:
- name: "model_amk_Reformat_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy_tmp_source__amk"
  database: "database"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "prophecy_tmp__mc4h8saj__amk__Reformat_1"
    tags:
    - "prophecy_temp"
